utils::globalVariables(
  c("y_col", "x_col", "xend_col", "yend_col", "maindata",
    "j", "xTGrid", "x", "y", "endX", "endY", "..level..",
    "player.name", "team.name", "fname", "lname", "pass.outcome.name",
    "location.x", "location.y", "pass.end_location.x", "pass.end_location.y",
    "end", "start", "isProg", "pass.cross", "pass.shot_assist", "delta_y", "colorOutcome", 
    "finalX", "finalY", "countPasses", "scouting_period", "Statistic", "Percentile",
    "Per90", "Player", "percentile", "X", "Y", "xG", "result", "isGoal",
    "ystart", "xstart", "slope", "startx", "starty", "pass.angle", "angle.round",
    "N", "n.angle", "maxN", "angle.norm", "pass.length", "frequency", "year",
    "season", "h_a", "home_team", "away_team", "home_away", "minute", "xGsum",
    "complete.cases", "Home", "Away", "Away_xG", "xGA", "xGSUM", "Date",
    "xGSM", "xGASM", "Home_xG", "distance",
    "events", "from", "outcome", "pass.recipient.name",
    "playerId", "player_label", "receiver", "teamId",
    "to", "type", "type.name", "xT", "xTEnd",
    "xTStart", "xend", "yend"))
